diigpageapp/app/urls.py
from .views import home, diig

from django.urls import path

app_name = 'App'

urlpatterns = [
    path('', home, name = 'inicio'),
    path('diig/', diig, name = 'diig'),
]

diigpageapp/business/urls.py
from django.urls import path

app_name = 'Business'

urlpatterns = [
    
]

diigpageapp/diigpageapp/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('escrito/', include('escrito.urls')),
    path('multimedia/', include('multimedia.urls')),
    path('users/', include('users.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diigpageapp/escrito/urls.py
from .views import posts_gallery, post_escrito

from django.urls import path

app_name = 'Escrito'

urlpatterns = [
    path('gallery/', posts_gallery, name='gallery'),
    path('<slug:slug>/', post_escrito, name='post_escrito')
]

diigpageapp/multimedia/urls.py
from .views import gallery_multimedia, post_multimedia

from django.urls import path

app_name = 'Multimedia'

urlpatterns = [
    path('multimedia/', gallery_multimedia, name='multi_gallery'),
    path('<slug:slug>/', post_multimedia, name='post_multimedia')
]

diigpageapp/users/urls.py
from .views import user_singup, user_login, user_logout

from django.urls import path

app_name = 'Users'

urlpatterns = [
    path('singup', user_singup, name='singup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
]

diigpageapp/app/models.py
from django.db import models

# Create your models here.

diigpageapp/business/models.py
from django.db import models

# Create your models here.

diigpageapp/escrito/models.py
from distutils.command import upload
from ckeditor.fields import RichTextField

from django.db import models
from django.db.models.base import Model
from django.db.models.fields import CharField


"""Here is the db models for the DIIG blog."""

class Autor(models.Model):
    
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre Autor', max_length=255, null=False, blank=False)
    status = models.BooleanField('Activo/Desactivado', default=True)
    pub_cre = models.DateField('Fecha de creación', auto_now=False, auto_now_add=True)

    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

    def __str__(self):
        return self.name
        

class Categoria_pub_escrita(models.Model):
    
    id = models.AutoField(primary_key = True)
    name = models.CharField(
        'Nombre de la categoria', max_length=100, null=False, blank=False
    )
    status = models.BooleanField('Categoria Activada/Desactivada', default=True)
    pub_cre = models.DateField('Fecha de creación', auto_now=False, auto_now_add=True)


    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

    def __str__(self):
        return self.name


class Post_escrito(models.Model):
    
    id = models.AutoField(primary_key=True)
    title = CharField('Titulo', max_length=90, blank=False, null=False)
    slug = models.CharField('Slug', max_length=100, blank=False, null=False)
    description = models.CharField('Descripción', max_length=510, blank=False, null=False)
    content = RichTextField()
    image = models.ImageField(upload_to='img', blank=True, null=True)
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria_pub_escrita, on_delete=models.CASCADE)
    status = models.BooleanField('Publicado/No Publicado', default=True)
    pub_cre = models.DateField('Fecha de Creación', auto_now=False, auto_now_add=True)
    pub_mod = models.DateField('Fecha Modificación', auto_now=True, auto_now_add=False)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title

diigpageapp/multimedia/models.py
from django.db import models

from escrito.models import Autor


class Categoria_pub_multimedia(models.Model):
    
    id = models.AutoField(primary_key = True)
    name = models.CharField(
        'Nombre de la categoria', max_length=100, null=False, blank=False
    )
    status = models.BooleanField('Categoria Activada/Desactivada', default=True)
    pub_cre = models.DateField('Fecha de creación', auto_now=False, auto_now_add=True)


    class Meta:
        verbose_name = 'Categoría'
        verbose_name_plural = 'Categorías'

    def __str__(self):
        return self.name


class Post_multimedia(models.Model):
    
    id = models.AutoField(primary_key = True)
    name = models.CharField(
        'Nombre del Set', max_length=255, null=False, blank=False                                        
    )
    pub_cre = models.DateField('Fecha de Creación', auto_now=False, auto_now_add=True)
    image = models.ImageField(upload_to='img', blank=True, null=True)
    autor = models.ForeignKey(
        Autor, 
        on_delete=models.CASCADE,
        related_name='Set',
    )
    categoria = models.ForeignKey(
        Categoria_pub_multimedia,
        on_delete=models.CASCADE,
    )
    archivo_multimedia = models.FileField(upload_to='video',max_length=255, blank=False, null=False)
    status = models.BooleanField('Publicado/No Publicado', default=True)
    description = models.CharField('Descripción', max_length=510, blank=False, null=True)
    slug = models.CharField('Slug', max_length=100, blank=False, null=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.name

diigpageapp/app/views.py
from django.shortcuts import render

def home(request):
    return render(request, "app/index.html")

def diig(request):
    return render(request, "app/diig.html")

diigpageapp/business/views.py
from django.shortcuts import render

# Create your views here.

diigpageapp/escrito/views.py
from email.mime import image
from multiprocessing import context
from django.shortcuts import render

from escrito.models import Post_escrito


def posts_gallery(request):

    total_posts = Post_escrito.objects.all()
    posts = total_posts.order_by('id').reverse()
    ultimate_post = total_posts.order_by('id').last()

    context = {
        'posts': posts,
        'ultimate_post': ultimate_post,
    }

    return render(request, "app/gallery_escrito.html", context)


def post_escrito(request, slug):

    post = Post_escrito.objects.get(
        slug = slug
    )

    context = {
        'post': post,
    }

    return render(request, "app/post_escrito.html", context)

diigpageapp/multimedia/views.py
from django.shortcuts import render
from multimedia.models import Post_multimedia


def gallery_multimedia(request):

    total_posts = Post_multimedia.objects.all()
    posts = total_posts.order_by('id').reverse()
    ultimate_post = total_posts.order_by('id').last()

    context = {
        "posts": posts,
        "ultimate_post": ultimate_post,
    }

    return render(request, 'app/gallery_multimedia.html', context)

def post_multimedia(request, slug):

    post = Post_multimedia.objects.get(
        slug = slug
    )

    context = {
        'post': post,
    }

    return render(request, "app/post_multimedia.html", context)

diigpageapp/users/views.py
from django.shortcuts import render


def user_singup(request):
    return render(request, 'app/singup.html')


def user_login(request):
    return render(request, 'app/login.html')


def user_logout(request):
    return render(request, 'app/logout.html')

diigpageapp/app/templates/app/diig.html
{% extends 'app/index.html' %}
{% load static %}

{% block head %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <meta name="description" content="Diego Guerrero a.k.a. DIIG es pythonista de corazón, estudiante de desarrollo backend con django e intelgencia artificial con TensorFlow en Platzi. También es DJ de géneros cómo: Techno, House o elektro y también estudia producción músical de manera autodidacta.">
  
  <meta name="robots" content="index, follow">
  <title>Galeria de Posts</title>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/home.css'%}" rel="stylesheet">
</head>
{% endblock head %}


{% block body %}
<body>
{% endblock body %}

{% block contenido %}
<main class="escrito-gallery-main">
    <section class="escrito-gallery-news-container">
        <div class="grid-container escrito-gallery-new">
            <h3>Biografía</h3>
            <div class="escrito-gallery-img-container">
                <img src="{% static 'media/img/dj_diig.jpg' %}" alt="imagen de post">
            </div>
            <div class="escrito-gallery-news-info-container">
                <h2>Quién es Diego Guerrero A.K.A. DIIG</h2>
                <p>Nacio el 26 de Diciembre de 1998 en la ciudad de Bogotá, Colombia. Desde pequeño fue un defensor del dialogo y la paz cómo método de resolución de conflictos. Apoyó firmemente los acuerdos de paz entre el gobierno Colombiano y las FARC en el 2016. Fue presidente del consejo de estudiantes y personero del colegio IED El Japón. Actualmente es DJ de musica electronica y estudiante de Desarrollo Backend, Ingenieria de Datos y Machine Learning con Python en Platzi. Al mismo tiempo se encuentra preparandose para ingresar a estudiar Física, entre otras cosas más.<br>
                <br>
                Se consiedera una persona bastante curiosa, que tiene muchas preguntas y muy pocas respuestas. Su meta en la vida es ayudar a otras personas, aprendiendo y enseñando sobre nuestra realidad, nuestro universo, nuestras relaciones humanas, entre otras cosas. Le gusta la filosofía moderna y le gustan las personas que se arriesgan por sus sueños y sus metas. 
                </p>
                <h4>Espero te guste este blog y explores todo mi sitio web ;)
                <br>
                <br>
                Atentamente, DIIG </h4>
            </div>
        </div>
    </section>
</main>

{% endblock contenido %}

diigpageapp/app/templates/app/gallery_escrito.html
{% extends 'app/index.html' %}
{% load static %}

{% block head %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <meta name="description" content="Diego Guerrero a.k.a. DIIG es pythonista de corazón, estudiante de desarrollo backend con django e intelgencia artificial con TensorFlow en Platzi. También es DJ de géneros cómo: Techno, House o elektro y también estudia producción músical de manera autodidacta.">
  
  <meta name="robots" content="index, follow">
  <title>Galeria de Posts</title>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/home.css'%}" rel="stylesheet">
</head>
{% endblock head %}

{% block body %}
<body>
{% endblock body %}

{% block contenido %}
<main class="escrito-gallery-main">
    
    <section class="escrito-gallery-news-container">
        {% if ultimate_post %}
        <div class="grid-container escrito-gallery-new">
            <h3>Ultima Publicación</h3>
            <div class="escrito-gallery-img-container">
                <img src="{{ultimate_post.image.url}}" alt="imagen de post">
            </div>
            <div class="escrito-gallery-news-info-container">
                <h2>{{ultimate_post.title}}</h2>
                <p>{{ultimate_post.description}}</p>
                <button class="escrito-gallery-buttons" style="margin-left: 10px;">
                    <a href="{% url 'Escrito:post_escrito' ultimate_post.slug %}">Leer</a>
                </button>
            </div>
        </div>
        {% else %}
        <H1>No hay Columnas en este momento</H1>
        {% endif %}
    </section>
    
    <section class="escrito-gallery-posts-container">
        <div class="grid-container">
            {% if posts %}
            <h3>Publicaciones Pasadas</h3>
            {% for post in posts %}
                <article class="escrito-gallery-posts-container">
                    <img src="{{post.image.url}}" alt="imagen post">
                    <p>{{post.title}}</p>
                    <p>{{post.description}}</p>
                    <button class="escrito-gallery-buttons" style="margin-left: 10px;">
                        <a href="{% url 'Escrito:post_escrito' post.slug %}">Leer</a>
                    </button>
                </article>
            {% endfor %}
            {% else %}
            <h1>No hay publicaciones pasadas.</h1>
            {% endif %}
        </div>
    </section>
</main>
<footer>
    <section>
        <div class="footer-icons">
            <a href="https://www.instagram.com/diig_guerrero1/"><img src="{% static 'media/img/instagram_logo.png' %}" alt="Instagram" width="25"></a>
            <a href="https://github.com/diigguerrero1"><img src="{% static 'media/img/github_logo.png' %}" alt="GitHub" width="25"></a>
            <a href="https://www.linkedin.com/in/diego-guerrero-01/"><img src="{% static 'media/img/linkedin_logo.png' %}" alt="LinkedIn" width="25"></a>
        </div>
    </section>
    <p>DIIG Guerrero Productions.</p>
</footer>

{% endblock contenido %}

diigpageapp/app/templates/app/gallery_multimedia.html
{% extends 'app/index.html' %}
{% load static %}

{% block head %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <meta name="description" content="Diego Guerrero a.k.a. DIIG es pythonista de corazón, estudiante de desarrollo backend con django e intelgencia artificial con TensorFlow en Platzi. También es DJ de géneros cómo: Techno, House o elektro y también estudia producción músical de manera autodidacta.">
  
  <meta name="robots" content="index, follow">
  <title>Galeria de DJ Sets</title>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/home.css'%}" rel="stylesheet">
</head>
{% endblock head %}

{% block body %}
<body>
{% endblock body %}

{% block contenido %}
<main class="escrito-gallery-main">
    <section class="escrito-gallery-news-container">
        <div class="grid-container escrito-gallery-new">
            <h3>Ultima Publicación</h3>
            <div class="escrito-gallery-img-container">
                <img src="{{ultimate_post.image.url}}" alt="imagen de post">
            </div>
            <div class="escrito-gallery-news-info-container">
                <h2>{{ultimate_post.name}}</h2>
                <p>{{ultimate_post.description}}</p>
                <button class="escrito-gallery-buttons" style="margin-left: 10px;">
                    <a href="{% url 'Multimedia:post_multimedia' ultimate_post.slug %}">Escuchar</a>
                </button>
            </div>
        </div>
    </section>
    <section class="escrito-gallery-posts-container">
        <div class="grid-container">
            <h3>Publicaciones Pasadas</h3>
            <article class="escrito-gallery-posts-container">
                {% for post in posts %}
                    <img src="{{post.image.url}}" alt="imagen post">
                    <p>{{post.name}}</p>
                    <p>{{post.description}}</p>
                    <button class="escrito-gallery-buttons" style="margin-left: 10px;">
                        <a href="{% url 'Multimedia:post_multimedia' post.slug %}">Escuchar</a>
                    </button>
                {% endfor %}
            </article>
        </div>
    </section>
</main>
<footer>
    <section>
        <div class="">
            <a href="https://www.instagram.com/diig_guerrero1/"><img src="{% static 'media/img/instagram_logo.png' %}" alt="Instagram" width="25"></a>
            <a href="https://github.com/diigguerrero1"><img src="{% static 'media/img/github_logo.png' %}" alt="GitHub" width="25"></a>
            <a href="https://www.linkedin.com/in/diego-guerrero-01/"><img src="{% static 'media/img/linkedin_logo.png' %}" alt="LinkedIn" width="25"></a>
        </div>
    </section>
    <p>DIIG Guerrero Productions.</p>
</footer>

{% endblock contenido %}

diigpageapp/app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

{% block head %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <meta name="description" content="Diego Guerrero a.k.a. DIIG es pythonista de corazón, estudiante de desarrollo backend con django e intelgencia artificial con TensorFlow en Platzi. También es DJ de géneros cómo: Techno, House o elektro y también estudia producción músical de manera autodidacta.">
  
  <meta name="robots" content="index, follow">
  <title>DIIG | Bienvenido</title>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/home.css'%}" rel="stylesheet">
</head>
{% endblock head %}

{% block body %}
<body class="index-body">
{% endblock body %}
    <header>
        <section class="header-icons-container">
            <div class="icons">
                <a href="https://www.instagram.com/diig_guerrero1/"><img src="{% static 'media/img/instagram_logo.png' %}" alt="Instagram" width="25"></a>
                <a href="https://github.com/diigguerrero1"><img src="{% static 'media/img/github_logo.png' %}" alt="GitHub" width="25"></a>
                <a href="https://www.linkedin.com/in/diego-guerrero-01/"><img src="{% static 'media/img/linkedin_logo.png' %}" alt="LinkedIn" width="25"></a>
            </div>
        </section>
        <nav>
            <section class="nav-logo-container">
                <a href="{% url 'App:inicio' %}"><img src="{% static 'media/img/logo_diig_with_smile-1.png' %}" alt="Logo DIIG" width="110"></a>
            </section>
            {% block segunda_seccion_nav %}
            <section class="profile-link">
                <a href="{% url 'App:diig' %}">Biografía</a>
            </section>
            {% endblock segunda_seccion_nav %}
        </nav>
    </header>

    {% block contenido %}

    <main class="home-main">
        <section class="section-main-text">
            <p class="home-main-text">Bienvenidos a este espacio singular</p>
            <p class="home-main-text">¿Qué deseas ver hoy?</p>
            <section class="section-main-buttons">
                <button class="home-main-buttons" style="margin: 10px;">
                <a href="{% url 'Escrito:gallery' %}">Columnas</a>
                </button>
                <button class="home-main-buttons" style="margin-left: 10px;">
                    <a href="{% url 'Multimedia:multi_gallery' %}">Sets</a>
                </button>
            </section>
        </section>
    </main>

    {% endblock contenido %}

</body>
</html>

diigpageapp/app/templates/app/post_escrito.html
{% extends 'app/index.html' %}
{% load static %}

{% block head %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <meta name="description" content="Diego Guerrero a.k.a. DIIG es pythonista de corazón, estudiante de desarrollo backend con django e intelgencia artificial con TensorFlow en Platzi. También es DJ de géneros cómo: Techno, House o elektro y también estudia producción músical de manera autodidacta.">
  
  <meta name="robots" content="index, follow">
  <title>{{post.title}}</title>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/home.css'%}" rel="stylesheet">
</head>
{% endblock head %}

{% block body %}
<body>
{% endblock body %}


{% block contenido %}
<main>
  <section class="escrito-post-img-container">
    <img src="{{post.image.url}}" alt="Foto Post">
  </section>
  <section class="escrito-post-main-container">
    <div class="grid-container">
      <h3>{{ post.categoria }}</h3>
      <article>
        <h1>{{ post.title }}</h1>
        {{ post.content | safe }}
      </article>
    </div>
  </section>
</main>

<footer>
    <div class="footer-icons">
      <a href="https://www.instagram.com/diig_guerrero1/"><img src="{% static 'media/img/instagram_logo.png' %}" alt="Instagram" width="25"></a>
      <a href="https://github.com/diigguerrero1"><img src="{% static 'media/img/github_logo.png' %}" alt="GitHub" width="25"></a>
      <a href="https://www.linkedin.com/in/diego-guerrero-01/"><img src="{% static 'media/img/linkedin_logo.png' %}" alt="LinkedIn" width="25"></a>
    </div>
  <p>DIIG Guerrero Productions.</p>
</footer>

{% endblock contenido %}

diigpageapp/app/templates/app/post_multimedia.html
{% extends 'app/index.html' %}
{% load static %}

{% block head %}
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 
  <meta name="description" content="Diego Guerrero a.k.a. DIIG es pythonista de corazón, estudiante de desarrollo backend con django e intelgencia artificial con TensorFlow en Platzi. También es DJ de géneros cómo: Techno, House o elektro y también estudia producción músical de manera autodidacta.">
  
  <meta name="robots" content="index, follow">
  <title>{{post.title}}</title>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/home.css'%}" rel="stylesheet">
</head>
{% endblock head %}

{% block body %}
<body>
{% endblock body %}


{% block contenido %}
<main>
  <section class="escrito-post-img-container">
    <video src="{{post.archivo_multimedia.url}}" controls></video>
  </section>
  <section class="escrito-post-main-container">
    <div class="grid-container">
      <h3>{{ post.name }}</h3>
      <article>
        {{ post.description }}
      </article>
    </div>
  </section>
</main>

<footer>
    <div class="footer-icons">
      <a href="https://www.instagram.com/diig_guerrero1/"><img src="{% static 'media/img/instagram_logo.png' %}" alt="Instagram" width="25"></a>
      <a href="https://github.com/diigguerrero1"><img src="{% static 'media/img/github_logo.png' %}" alt="GitHub" width="25"></a>
      <a href="https://www.linkedin.com/in/diego-guerrero-01/"><img src="{% static 'media/img/linkedin_logo.png' %}" alt="LinkedIn" width="25"></a>
    </div>
  <p>DIIG Guerrero Productions.</p>
</footer>

{% endblock contenido %}